Celma: celma::prog_args::detail::IConstraint Class Reference
celma::prog_args::detail::IConstraint Class Reference abstract
Base class for constraints.
#include <i_constraint.hpp>
Public Member Functions
virtual ~IConstraint ()
Empty, virtual destructor required for base classes.
virtual void executeConstraint (const std::string &sourceArg)=0
Called when an argument was identified and the corresponding handler called.
virtual std::string & argumentList ()
Needed on global constraints: The list of arguments for which the constraint is defined.
virtual void validated ()
Called after the argument list in a global constraint was validated.
virtual void checkEndCondition () const
Needed on global constraints: Called when all arguments were evaluated, has to check if the constraint was fulfilled.
Static Protected Member Functions
static bool isConstraintArgument (const std::string &constraint_arg_list, const std::string &arg_spec)
Checks if the argument specified in arg_spec is one of the argument(s) specified in the constraint_arg_list.
Detailed Description
Base class for constraints.
Actually this base class is used for two different types of constraints:
Constraints depending on a specific argument, dynamically activated if the argument is used.
So-called 'global constraint's which affect multiple arguments and are stored/handled in the argument handler itself.
Since
0.2, 10.04.2016
Definition at line 35 of file i_constraint.hpp.
Constructor & Destructor Documentation
virtual celma::prog_args::detail::IConstraint::~IConstraint () inline virtual
Empty, virtual destructor required for base classes.
Since
0.2, 10.04.2016
Definition at line 40 of file i_constraint.hpp.
Member Function Documentation
string & celma::prog_args::detail::IConstraint::argumentList () virtual
Needed on global constraints: The list of arguments for which the constraint is defined.
Returns
The list arguments affected by the constraint.
Since
0.2, 10.04.2016
Reimplemented in celma::prog_args::detail::ConstraintAllOf, celma::prog_args::detail::ConstraintAnyOf, and celma::prog_args::detail::ConstraintOneOf.
Definition at line 41 of file i_constraint.cpp.
Referenced by celma::prog_args::Handler::addConstraint(), and ~IConstraint().
void celma::prog_args::detail::IConstraint::checkEndCondition () const virtual
Needed on global constraints: Called when all arguments were evaluated, has to check if the constraint was fulfilled.
Since
0.2, 10.04.2016
Reimplemented in celma::prog_args::detail::ConstraintAllOf, celma::prog_args::detail::ConstraintAnyOf, and celma::prog_args::detail::ConstraintOneOf.
Definition at line 62 of file i_constraint.cpp.
Referenced by ~IConstraint().
virtual void celma::prog_args::detail::IConstraint::executeConstraint (const std::string & sourceArg) pure virtual
Called when an argument was identified and the corresponding handler called.
Since
0.2, 10.04.2016
Implemented in celma::prog_args::detail::ConstraintAllOf, celma::prog_args::detail::ConstraintAnyOf, celma::prog_args::detail::ConstraintExcludes, celma::prog_args::detail::ConstraintOneOf, and celma::prog_args::detail::ConstraintRequires.
Referenced by ~IConstraint().
bool celma::prog_args::detail::IConstraint::isConstraintArgument (const std::string & constraint_arg_list, const std::string & arg_spec) static protected
Checks if the argument specified in arg_spec is one of the argument(s) specified in the constraint_arg_list.
This method is used by global constraints derived from this base class, because their executeConstraint() method is called for each argument found on the command line.
Parameters
[in] constraint_arg_list The list of argument(s) for which the constraint is defined.
[in] arg_spec The specification of the argument just found in the argument string.
Returns
true if the specified argument is in the list of constrained arguments.
Since
0.2, 10.04.2016
Definition at line 82 of file i_constraint.cpp.
Referenced by celma::prog_args::detail::ConstraintOneOf::executeConstraint(), celma::prog_args::detail::ConstraintAnyOf::executeConstraint(), celma::prog_args::detail::ConstraintAllOf::executeConstraint(), and ~IConstraint().
void celma::prog_args::detail::IConstraint::validated () virtual
Called after the argument list in a global constraint was validated.
Since
0.2, 10.04.2016
Reimplemented in celma::prog_args::detail::ConstraintAllOf, celma::prog_args::detail::ConstraintAnyOf, and celma::prog_args::detail::ConstraintOneOf.
Definition at line 51 of file i_constraint.cpp.
Referenced by celma::prog_args::Handler::addConstraint(), and ~IConstraint().
The documentation for this class was generated from the following files:
src/celma/prog_args/detail/i_constraint.hpp
src/library/prog_args/detail/i_constraint.cpp