Celma: celma::prog_args::detail::ArgListParser Class Reference
celma::prog_args::detail::ArgListParser Class Reference
This class allows to handle an argument list one element after the other.
#include <arg_list_parser.hpp>
Public Types
typedef ArgListIterator< ArgListParser, ArgListElement > const_iterator
The type of the iterator.
Public Member Functions
ArgListParser (int argc, char *argv[])
Constructor.
int argCount () const
Returns the number of argument strings (as passed to the constructor).
char ** argVector () const
Returns pointer to the array of argument strings (as passed to the constructor).
const_iterator begin () const
Returns the iterator pointing to the first argument.
const_iterator end () const
Returns the iterator pointing behind the last argument.
const_iterator cbegin () const
Returns the iterator pointing to the first argument.
const_iterator cend () const
Returns the iterator pointing behind the last argument.
Private Attributes
int mArgCount
Number of argument strings.
char ** mpArgV
Array of argument strings.
Detailed Description
This class allows to handle an argument list one element after the other.
Here we don't know which arguments are mandatory, or if a value belongs to the previous argument or if it is a positional value. We just parse the argument list, separate groups of multiple single character arguments and separate long arguments from their values.
Since
0.2, 09.04.2016
Definition at line 35 of file arg_list_parser.hpp.
Member Typedef Documentation
typedef ArgListIterator< ArgListParser, ArgListElement> celma::prog_args::detail::ArgListParser::const_iterator
The type of the iterator.
Definition at line 56 of file arg_list_parser.hpp.
Constructor & Destructor Documentation
celma::prog_args::detail::ArgListParser::ArgListParser (int argc, char * argv[])
Constructor.
Parameters
[in] argc Number of argument strings in the array.
[in] argv[] Array of argument strings.
Since
0.2, 09.04.2016
Definition at line 32 of file arg_list_parser.cpp.
Member Function Documentation
int celma::prog_args::detail::ArgListParser::argCount () const inline
Returns the number of argument strings (as passed to the constructor).
Returns
Number of argument strings.
Since
0.2, 09.04.2016
Definition at line 91 of file arg_list_parser.hpp.
char ** celma::prog_args::detail::ArgListParser::argVector () const inline
Returns pointer to the array of argument strings (as passed to the constructor).
Returns
Pointer to the beginning of the array of argument strings.
Since
0.2, 09.04.2016
Definition at line 97 of file arg_list_parser.hpp.
ArgListParser::const_iterator celma::prog_args::detail::ArgListParser::begin () const
Returns the iterator pointing to the first argument.
Returns
Iterator pointing to the first argument.
Since
0.2, 09.04.2016
Definition at line 43 of file arg_list_parser.cpp.
Referenced by celma::prog_args::Groups::evalArguments(), and celma::prog_args::Handler::iterateArguments().
ArgListParser::const_iterator celma::prog_args::detail::ArgListParser::cbegin () const
Returns the iterator pointing to the first argument.
Returns
Iterator pointing to the first argument.
Since
0.2, 09.04.2016
Definition at line 63 of file arg_list_parser.cpp.
ArgListParser::const_iterator celma::prog_args::detail::ArgListParser::cend () const
Returns the iterator pointing behind the last argument.
Returns
Iterator pointing behind the last argument.
Since
0.2, 09.04.2016
Definition at line 73 of file arg_list_parser.cpp.
ArgListParser::const_iterator celma::prog_args::detail::ArgListParser::end () const
Returns the iterator pointing behind the last argument.
Returns
Iterator pointing behind the last argument.
Since
0.2, 09.04.2016
Definition at line 53 of file arg_list_parser.cpp.
Referenced by celma::prog_args::Groups::evalArguments(), and celma::prog_args::Handler::iterateArguments().
Member Data Documentation
int celma::prog_args::detail::ArgListParser::mArgCount private
Number of argument strings.
Definition at line 80 of file arg_list_parser.hpp.
Referenced by argCount().
char** celma::prog_args::detail::ArgListParser::mpArgV private
Array of argument strings.
Definition at line 82 of file arg_list_parser.hpp.
Referenced by argVector().
The documentation for this class was generated from the following files:
src/celma/prog_args/detail/arg_list_parser.hpp
src/library/prog_args/detail/arg_list_parser.cpp