Celma: celma::prog_args::IUsageText Class Reference
celma::prog_args::IUsageText Class Reference abstract
Base class for classes that print additional information for the usage.
#include <i_usage_text.hpp>
Public Member Functions
IUsageText (Handler::UsagePos up)
Constructor.
virtual ~IUsageText ()=default
Empty, virtual destructor.
virtual void print (std::ostream &os) const =0
Defines the interface function.
Handler::UsagePos usagePos () const
Returns the position of the text in the usage as specified in the constructor.
Private Attributes
const Handler::UsagePos mUsagePos
The position of the text in the usage.
Friends
std::ostream & operator<< (std::ostream &os, IUsageText *pObj)
Prints the contents of the class/object derived from this base class.
Detailed Description
Base class for classes that print additional information for the usage.
Together with the following macro UsageText(), the additional usage output can be created very easily.
Example:
Define the text to print before the list of arguments:
     UsageText( PreArgText,
                "Additional text to print before the arguments"
              );
Pass the information like this:
     ArgumentHandler::evalArguments( argc, argv,
                                     ArgumentHandler::upBeforeArgs,
                                     PreArgText);
Since
0.2, 10.04.2016
Definition at line 46 of file i_usage_text.hpp.
Constructor & Destructor Documentation
celma::prog_args::IUsageText::IUsageText (Handler::UsagePos up) inline
Constructor.
Parameters
[in] up The position of the text, provided by this object, in the usage.
Since
0.2, 10.04.2016
Definition at line 53 of file i_usage_text.hpp.
virtual celma::prog_args::IUsageText::~IUsageText () virtual default
Empty, virtual destructor.
Since
0.2, 10.04.2016
Referenced by IUsageText().
Member Function Documentation
virtual void celma::prog_args::IUsageText::print (std::ostream & os) const pure virtual
Defines the interface function.
Parameters
[out] os The stream to write the output to.
Since
0.2, 10.04.2016
Referenced by IUsageText().
Handler::UsagePos celma::prog_args::IUsageText::usagePos () const inline
Returns the position of the text in the usage as specified in the constructor.
Returns
The defined position for the text.
Since
0.2, 10.04.2016
Definition at line 71 of file i_usage_text.hpp.
Referenced by celma::prog_args::Groups::displayUsage(), and celma::prog_args::Handler::usage().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, IUsageText * pObj) friend
Prints the contents of the class/object derived from this base class.
Parameters
[out] os The stream to write to.
[in] pObj Pointer to the object to dumpt the contents of.
Returns
The stream as passed as parameter.
Since
0.2, 10.04.2016
Definition at line 81 of file i_usage_text.hpp.
Member Data Documentation
const Handler::UsagePos celma::prog_args::IUsageText::mUsagePos private
The position of the text in the usage.
Definition at line 89 of file i_usage_text.hpp.
Referenced by usagePos().
The documentation for this class was generated from the following file:
src/celma/prog_args/i_usage_text.hpp