Celma: celma::type< T > Class Template Reference
celma::type< T > Class Template Reference
Base template for getting the name of a type.
#include <type_name.hpp>
Static Public Member Functions
static constexpr const char * name ()
Returns the name of the type.
Detailed Description
template<typename T>
class celma::type< T >
Base template for getting the name of a type.
Partial template specialisation is used to provide the name of a type.
The design with the static method was chosen because the solution with a static member variable led to 'multiple instance' error messages. Maybe this would not happen with C++11x 'constexpr'.
The template was added to the 'std' namespace on purpose.
Template Parameters
T The type to provide the name of.
Since
0.1, 15.03.2016
Definition at line 32 of file type_name.hpp.
Member Function Documentation
template<typename T > static constexpr const char* celma::type< T >::name () inline static
Returns the name of the type.
Returns
'unknown'.
Since
0.1, 15.03.2016
Definition at line 38 of file type_name.hpp.
Referenced by celma::prog_args::detail::TypedArgPair< T1, T2 >::dump(), celma::prog_args::detail::TypedArgRange< T, C >::dump(), celma::prog_args::detail::TypedArg< T >::dump(), celma::prog_args::detail::TypedArg< common::CheckAssign< T > >::dump(), celma::prog_args::detail::TypedArg< std::vector< T > >::dump(), and celma::common::var::name().
The documentation for this class was generated from the following file:
src/celma/detail/type_name.hpp