Celma: celma::prog_args::detail::ICardinality Class Reference
celma::prog_args::detail::ICardinality Class Reference abstract
Base class for implementation of cardinality checks.
#include <i_cardinality.hpp>
Public Member Functions
virtual ~ICardinality ()
Empty, virtual destructor.
virtual void gotValue ()=0
Called by the framework when the argument was detected in the command line (actually may be without a value).
virtual void check ()=0
Called by the framework at the end of the command line processing.
Protected Member Functions
ICardinality ()
Constructor.
Protected Attributes
int mNumValues
Counter for the number of calls/values.
Detailed Description
Base class for implementation of cardinality checks.
Derived classes must implement both methods:
gotValue() is called every time before assign() is called for the argument.
check() is called after all arguments were evaluated, should check if e.g. minimum requirements were met.
If a cardinality check fails, the method(s) should throw an exception.
Since
0.2, 10.04.2016
Definition at line 33 of file i_cardinality.hpp.
Constructor & Destructor Documentation
virtual celma::prog_args::detail::ICardinality::~ICardinality () inline virtual
Empty, virtual destructor.
Since
0.2, 10.04.2016
Definition at line 38 of file i_cardinality.hpp.
celma::prog_args::detail::ICardinality::ICardinality () inline protected
Constructor.
Does not really need to be protected, but emphasizes the point that objects of this class can only be created through classes derived from it.
Since
0.2, 10.04.2016
Definition at line 66 of file i_cardinality.hpp.
Referenced by ~ICardinality().
Member Function Documentation
virtual void celma::prog_args::detail::ICardinality::check () pure virtual
Called by the framework at the end of the command line processing.
Since
0.2, 10.04.2016
Implemented in celma::prog_args::detail::CardinalityRange, celma::prog_args::detail::CardinalityExact, and celma::prog_args::detail::CardinalityMax.
Referenced by ~ICardinality().
virtual void celma::prog_args::detail::ICardinality::gotValue () pure virtual
Called by the framework when the argument was detected in the command line (actually may be without a value).
Since
0.2, 10.04.2016
Implemented in celma::prog_args::detail::CardinalityRange, celma::prog_args::detail::CardinalityExact, and celma::prog_args::detail::CardinalityMax.
Referenced by ~ICardinality().
Member Data Documentation
int celma::prog_args::detail::ICardinality::mNumValues protected
Counter for the number of calls/values.
Definition at line 57 of file i_cardinality.hpp.
Referenced by celma::prog_args::detail::CardinalityExact::check(), celma::prog_args::detail::CardinalityRange::check(), celma::prog_args::detail::CardinalityMax::gotValue(), celma::prog_args::detail::CardinalityExact::gotValue(), and celma::prog_args::detail::CardinalityRange::gotValue().
The documentation for this class was generated from the following file:
src/celma/prog_args/detail/i_cardinality.hpp