Celma: celma::common::RangeExpression Class Reference
celma::common::RangeExpression Class Reference
Helper class to extract the different parts of a range expression.
#include <range_expression.hpp>
Public Member Functions
RangeExpression ()
Constructor, initialises the regular expression.
void parseString (const std::string &s)
Parses the (first) range expression in the string.
const std::string & matchedExpression () const
Returns the full string that was matched.
int64_t startValue () const
Returns the single/range start value.
bool hasRangeEnd () const
Returns if an end-value was found in the string.
int64_t endValue () const
Returns the range end value, if one was set.
bool hasIncrement () const
Returns if an increment value was found in the string.
int64_t incrementValue () const
Returns the range increment value, if one was set.
bool hasExcludeExpr () const
Returns if an exclude expression was found in the string.
const std::string & excludeExpression () const
Returns the range exclude expression, if one was set.
Private Types
enum MatchIndex { miStartValue = 0x01, miEndValue = miStartValue << 1, miIncrement = miEndValue << 1, miExclude = miIncrement << 1 }
Indices to the match object:
Private Member Functions
bool parse ()
Parses the string starting from mNextPos, checks and evaluates the single values, ranges, steps etc.
void readNumber (int64_t &value)
Helper function to read a number from the range string.
Private Attributes
std::string mRangeString
Copy of the range string that we parse.
std::string mMatchedExpression
Whole matched expression.
int mFound
Set of flags, which values/expressions were found in the range string.
int64_t mStartValue
Single/Range start value.
int64_t mEndValue
Range end value.
int64_t mIncrementValue
Range increment value.
std::string mExcludeValue
Range exclude value.
std::string::size_type mNextPos
The position in the string to parse.
Detailed Description
Helper class to extract the different parts of a range expression.
After parsing an expression with parseString(), check the strings for the results:
matchedExpression() returns the full expression that was matched. If this string is empty, the string did not contain a valid range expression.
startValue() contains the single/range start value.
endValue() contains the range end value, if a range was defined.
incrementValue() contains the increment value for the range, may be empty.
excludeExpression() contains the expression for the values to exclude, may be empty.
Since
0.2, 07.04.2016
Definition at line 41 of file range_expression.hpp.
Member Enumeration Documentation
enum celma::common::RangeExpression::MatchIndex private
Indices to the match object:
Enumerator
miStartValue
Single/range start value.
miEndValue
Range end value.
miIncrement
Range increment value.
miExclude
Range exclude expression.
Definition at line 97 of file range_expression.hpp.
Constructor & Destructor Documentation
celma::common::RangeExpression::RangeExpression ()
Constructor, initialises the regular expression.
Since
0.2, 07.04.2016
Definition at line 43 of file range_expression.cpp.
Member Function Documentation
int64_t celma::common::RangeExpression::endValue () const inline
Returns the range end value, if one was set.
Returns
The range end value, may be empty.
Since
0.2, 07.04.2016
Definition at line 158 of file range_expression.hpp.
Referenced by celma::common::RangeStringIterator< T, TF >::createRanger().
const std::string & celma::common::RangeExpression::excludeExpression () const inline
Returns the range exclude expression, if one was set.
Returns
The range exclude expression, may be empty.
Since
0.2, 07.04.2016
Definition at line 182 of file range_expression.hpp.
Referenced by celma::common::RangeStringIterator< T, TF >::createRanger().
bool celma::common::RangeExpression::hasExcludeExpr () const inline
Returns if an exclude expression was found in the string.
Returns
true if an exclude expression was found in the string.
Since
0.2, 07.04.2016
Definition at line 176 of file range_expression.hpp.
Referenced by celma::common::RangeStringIterator< T, TF >::createRanger().
bool celma::common::RangeExpression::hasIncrement () const inline
Returns if an increment value was found in the string.
Returns
true if an increment value was found in the string.
Since
0.2, 07.04.2016
Definition at line 164 of file range_expression.hpp.
Referenced by celma::common::RangeStringIterator< T, TF >::createRanger().
bool celma::common::RangeExpression::hasRangeEnd () const inline
Returns if an end-value was found in the string.
Returns
true if an end-value was found in the string.
Since
0.2, 07.04.2016
Definition at line 152 of file range_expression.hpp.
Referenced by celma::common::RangeStringIterator< T, TF >::createRanger().
int64_t celma::common::RangeExpression::incrementValue () const inline
Returns the range increment value, if one was set.
Returns
The range increment value, may be empty.
Since
0.2, 07.04.2016
Definition at line 170 of file range_expression.hpp.
Referenced by celma::common::RangeStringIterator< T, TF >::createRanger().
const std::string & celma::common::RangeExpression::matchedExpression () const inline
Returns the full string that was matched.
Returns
The string that was matched.
Since
0.2, 07.04.2016
Definition at line 140 of file range_expression.hpp.
Referenced by celma::common::RangeStringIterator< T, TF >::operator++(), and celma::common::RangeStringIterator< T, TF >::RangeStringIterator().
bool celma::common::RangeExpression::parse () private
Parses the string starting from mNextPos, checks and evaluates the single values, ranges, steps etc.
Returns
true if the contents of the string are syntactically correct.
Since
0.2, 07.04.2016
Definition at line 86 of file range_expression.cpp.
Referenced by parseString().
void celma::common::RangeExpression::parseString (const std::string & s)
Parses the (first) range expression in the string.
The string must begin with a valid range expression. Everything after the parts that could be identified is ignored.
Parameters
[in] s The string to parse.
Since
0.2, 07.04.2016
Definition at line 61 of file range_expression.cpp.
Referenced by celma::common::RangeStringIterator< T, TF >::operator++(), and celma::common::RangeStringIterator< T, TF >::RangeStringIterator().
void celma::common::RangeExpression::readNumber (int64_t & value) private
Helper function to read a number from the range string.
Parameters
[out] value Returns the value read from the string.
Since
0.2, 07.04.2016
Definition at line 170 of file range_expression.cpp.
Referenced by parse().
int64_t celma::common::RangeExpression::startValue () const inline
Returns the single/range start value.
Returns
The start value.
Since
0.2, 07.04.2016
Definition at line 146 of file range_expression.hpp.
Referenced by celma::common::RangeStringIterator< T, TF >::createRanger().
Member Data Documentation
int64_t celma::common::RangeExpression::mEndValue private
Range end value.
Definition at line 125 of file range_expression.hpp.
Referenced by endValue(), parse(), and parseString().
std::string celma::common::RangeExpression::mExcludeValue private
Range exclude value.
Definition at line 129 of file range_expression.hpp.
Referenced by excludeExpression(), parse(), and parseString().
int celma::common::RangeExpression::mFound private
Set of flags, which values/expressions were found in the range string.
Definition at line 121 of file range_expression.hpp.
Referenced by hasExcludeExpr(), hasIncrement(), hasRangeEnd(), parse(), and parseString().
int64_t celma::common::RangeExpression::mIncrementValue private
Range increment value.
Definition at line 127 of file range_expression.hpp.
Referenced by incrementValue(), parse(), and parseString().
std::string celma::common::RangeExpression::mMatchedExpression private
Whole matched expression.
Definition at line 119 of file range_expression.hpp.
Referenced by matchedExpression(), and parseString().
std::string::size_type celma::common::RangeExpression::mNextPos private
The position in the string to parse.
Definition at line 131 of file range_expression.hpp.
Referenced by parse(), parseString(), and readNumber().
std::string celma::common::RangeExpression::mRangeString private
Copy of the range string that we parse.
Definition at line 117 of file range_expression.hpp.
Referenced by parse(), parseString(), and readNumber().
int64_t celma::common::RangeExpression::mStartValue private
Single/Range start value.
Definition at line 123 of file range_expression.hpp.
Referenced by parse(), parseString(), and startValue().
The documentation for this class was generated from the following files:
src/celma/common/range_expression.hpp
src/library/common/range_expression.cpp