Celma: celma::prog_args::Handler Class Reference
celma::prog_args::Handler Class Reference
Class to store all command line argument descriptions as well as the destination variables to store the values in.
#include <handler.hpp>
Public Types
enum HandleFlags {
hfHelpShort = 0x01, hfHelpLong = hfHelpShort << 1, hfReadProgArg = hfHelpLong << 1, hfVerboseArgs = hfReadProgArg << 1,
hfUsageHidden = hfVerboseArgs << 1, hfArgHidden = hfUsageHidden << 1, hfListArgVar = hfArgHidden << 1, hfUsageCont = hfListArgVar << 1,
hfEndValues = hfUsageCont << 1
}
List of flags to control the behaviour of this class:
enum UsagePos { upUnused, upBeforeArgs, upAfterArgs }
List of possible positions for the additional output.
typedef boost::function< void()> HandlerFunc
Type of the (storage handler of the) functions to call for control characters.
Public Member Functions
Handler (int flagSet=hfHelpShort|hfHelpLong, IUsageText *txt1=nullptr, IUsageText *txt2=nullptr)
Constructor.
Handler (std::ostream &os, std::ostream &error_os, int flag_set=hfHelpShort|hfHelpLong, IUsageText *txt1=nullptr, IUsageText *txt2=nullptr)
Constructor that allows to specify the output streams to write to.
~Handler ()
Destructor, deletes dynamically allocated objects.
template<typename T >
detail::TypedArgBase * addArgument (const std::string &arg_spec, T &dest, const std::string vname, const std::string &desc)
Adds a single-value argument.
template<typename T1 , typename T2 >
detail::TypedArgBase * addArgument (const std::string &arg_spec, T1 &dest1, const std::string vname1, T2 &dest2, const std::string vname2, const T2 &value2, const std::string &desc)
Adds a single-value argument where an additional value is set on a second variable when the parameter is used.
template<typename T >
detail::TypedArgBase * addArgument (T &dest, const std::string vname, const std::string &desc)
Adds a free, single-value argument.
template<typename T , typename C >
detail::TypedArgBase * addArgument (const std::string &arg_spec, const common::RangeDest< T, C > &dest, const std::string vname, const std::string &desc)
Adds a multi-value argument that supports a range definition string for the values.
template<typename T , typename C >
detail::TypedArgBase * addArgument (const common::RangeDest< T, C > &dest, const std::string vname, const std::string &desc)
Adds a free, multi-value argument that supports a range definition string for the values.
detail::TypedArgBase * addArgument (const std::string &arg_spec, detail::ArgHandlerCallable fun, const std::string fname, const std::string &desc)
Adds an argument handler function that is called when an argument that does not accept any value is set.
detail::TypedArgBase * addArgument (const std::string &arg_spec, detail::ArgHandlerCallableValue fun, const std::string fname, bool takes_value, const std::string &desc)
Adds an argument handler function that is called when an argument that may accept or requires a parameter is set.
detail::TypedArgBase * addArgument (const std::string &arg_spec, Handler *subGroup, const std::string &desc)
Adds a sub-group.
detail::TypedArgBase * addArgumentFile (const std::string &arg_spec)
Adds an argument that takes the path/filename of an argument file as parameter.
detail::TypedArgBase * addArgumentPrintHidden (const std::string &arg_spec)
Adds an argument that activates printing of hidden arguments in the usage.
detail::TypedArgBase * addArgumentListArgVars (const std::string &arg_spec)
Adds an argument that prints the list of arguments, their destination variables and their values.
detail::TypedArgBase * addArgumentEndValues (const std::string &arg_spec)
Adds an argument that can be used to mark the end of multiple, separate value list.
template<typename C , typename T >
detail::TypedArgBase * addCustomArgument (const std::string &arg_spec, T &dest, const std::string vname, const std::string &desc)
Adds an argument with a custom destination type.
void addControlHandler (char ctrlChar, HandlerFunc hf)
Specifies the callback function for a control argument.
void setUsageLineLength (int useLen)
Specifies the line length to use when printing the usage.
void addConstraint (detail::IConstraint *ic)
Adds a constraint to the argument handler itself that affects multiple arguments.
void evalArguments (int argc, char *argv[])
Iterates over the list of arguments and their values and stores the values in the corresponding destination variables.
void evalArgumentsErrorExit (int argc, char *argv[], const std::string &prefix)
Same as evalArguments().
Static Public Attributes
static const int AllHelp = hfHelpShort | hfHelpLong
Set of all help arguments.
static const int AllFlags = hfHelpShort | hfHelpLong | hfReadProgArg
Set of available standard/commonly used arguments.
static const int DebugFlags = hfVerboseArgs | hfListArgVar
Flags for testing/debugging the module itself.
static const int FullFlagSet
Complete set of all available arguments.
Protected Types
enum ArgResult { arUnknown, arConsumed }
Function call result for evalSingleArgument():
Protected Member Functions
void crossCheckArguments (const std::string ownName, const std::string &otherName, const Handler &otherAH) const
Compares the arguments defined in this object with those in otherAH and throws an exception if duplicates are detected.
ArgResult evalSingleArgument (detail::ArgListParser::const_iterator &ai, const detail::ArgListParser::const_iterator &end)
Handles one argument.
void checkMissingMandatoryCardinality () const
Checks if all mandatory arguments were set, and the cardinality requirements were met.
void checkMaxArgLen (size_t &maxArgLen)
Checks and sets the maximum argument length, needed to format the usage.
bool argumentExists (char argChar) const
Checks if the specified argument is already used.
bool argumentExists (const std::string &argString) const
Checks if the specified argument is already used.
Private Types
typedef std::vector< detail::IConstraint * > ConstraintCont
Type of the container to store the global constrainst in.
Private Member Functions
void usage (IUsageText *txt1, IUsageText *txt2)
Function to print the usage of a program (when requested through the arguments).
void setIsSubGroupHandler ()
Sets the flag that this object is used as sub-group handler.
template<typename T >
ArgResult processArg (const T &arg, const std::string &argString, detail::ArgListParser::const_iterator &ai, const detail::ArgListParser::const_iterator &end)
The handling of single character arguments and argument strings/names is of course completely the same, except for the argument and its type.
void readEvalFileArguments (const char *arg0)
Tries to open the file with the program's name and read the arguments from this file.
void readArgumentFile (const std::string &pathFilename, bool reportMissing)
Function to read arguments from a file.
void listArgVars ()
Prints the list of arguments and their destination variables.
void endValueList ()
Called to mark the end of a value list: Sets mpLastArg to NULL.
void iterateArguments (detail::ArgListParser &alp)
Iterates over the arguments and evaluates them.
detail::TypedArgBase * internAddArgument (detail::TypedArgBase *ah_obj, const std::string &arg_spec, const std::string &desc)
Standard procedure for adding an argument handling object.
bool validArguments (std::string &constraint_arg_list) const
Checks each argument in the list if it is a valid/known argument.
void executeGlobalConstraints (const std::string &arg_spec)
When an argument was identified, passes the argument specification to all global constraint objects to check if a constraint is violated.
void checkGlobalConstraints () const
After all arguments were processed, call this method to iterate over all global constraints to check e.g.
void handleIdentifiedArg (detail::TypedArgBase *hdl, const std::string &arg_spec, const std::string &value="")
Called when a valid argument was identified.
Private Attributes
std::ostream & mOutput
Stream to write output to.
std::ostream & mErrorOutput
Stream to write error output to.
const bool mReadProgramArguments
Set when the flag hfReadProgArg was passed to the constructor.
const bool mVerbose
Set when the flag hfVerboseArgs was passed to the constructor.
bool mPrintHidden
Set when the flag hfUsageHidden was passed to the constructor.
const bool mUsageContinues
Set when the flag hfUsageCont was passed to the constructor.
bool mUsagePrinted
Set when the usage was printed.
detail::ArgumentContainer mArguments
The (top-level) arguments known by this class.
detail::ArgumentContainer mSubGroupArgs
Argument sub-groups.
detail::ArgumentDesc mDescription
Storage for the arguments and their descriptions.
HandlerFunc mpOpeningBracketHdlr
Function called for an opening bracket '('.
HandlerFunc mpClosingBracketHdlr
Function called for a closing bracket ')'.
HandlerFunc mpExclamationMarkHdlr
Function called for an exclamation mark '!'.
bool mIsSubGroupHandler
Set when this object is used as argument handler for a sub-group.
detail::ConstraintContainer mConstraints
The current constraints, dynamically created through the arguments that were processed so far.
ConstraintCont mGlobalConstraints
Global constraints, i.e.
detail::TypedArgBase * mpLastArg
Pointer to the last argument handler that was used.
bool mReadingArgumentFile
Reading arguments from a file should not influence the cardinality checks, i.e.
Friends
class Groups
Class needs access to internals.
std::ostream & operator<< (std::ostream &os, const Handler &ah)
Prints the usage of this class.
Detailed Description
Class to store all command line argument descriptions as well as the destination variables to store the values in.
To set up an argument handler, simply follow these steps:
Create object, specify the HandleFlags to get the desired behaviour.
For each argument, call addArgument() with the strings that specify the short and/or long arguments, the destination variable to store the value in when the argument is used (using the macro DEST_VAR()) plus a description of the argument and its value (for the usage).
The short (character) and long argument format are order independent in the argument string. Example: addArgument("s,silent", DEST_VAR(mRunSilent), "Set to suppress output");
For free (i.e. positional) arguments, simply pass an empty string for the arguments:
Example: addArgument("", DEST_VAR(mHostname), "The name of the host to connect to");
For each argument, you can specify if it requires a value or not.
Internally, the following defaults are applied:
Arguments used to set a boolean variable don't accept a value.
All other arguments require a value.
To change this 'value mode', call the function setValueMode() with the desired value.
Example: addArgument("v,verbose-level", DEST_VAR(mRunSilent), "Specifies the verbose level, if set without value default is 'low'")->setValueMode(vmOptional);
Additionally you can use the following modifiers for each argument to further specify the handling of the argument and its value:
setIsMandatory(): specifies that this argument is mandatory
addCheck(): Allows to add a value check. Possible checks are
lower: Lower limit for values to accept (inclusive).
upper: Upper limit for values to accept (exclusive).
range: Range of values for scalar types to accept.
values: List of values to accept.
usetFlag(): For destination variable type boolean: Instead of setting the variable to true when the argument is used, set it to false.
setPrintDefault(): Specifies if the default value (of the destination variable) should be printed in the usage.
setIsHidden(): Can be used to make an argument a hidden argument, i.e. it will not be listed in the usage.
setTakesMultiValue(): For destination types vector and callables: The destination type is able to process multiple, separate values.
addFormat(): Adds a format converter, can be used e.g. to convert symbolic names into integer values.
setListSep(): For destination type vector, allows to specify the list separator character by which a list of values is split.
setCardinality(): Allows to change or delete the cardinality check that is applied to this argument.
It is possible to add multiple checks to the same argument. In this case, a value must be accepted by all checks. The checks are executed in the order in which they were added.
Example: addArgument("f,factor>", DEST_VAR(myFactor), "Factor")->addCheck(range(1.0, 100.0));
Finally, when all arguments were specified, call evalArguments() to actually evaluate the command line arguments.
You can use this class to print a list of the arguments and their descriptions with usage(). The arguments are printed in the order in which they were added.
You can extend arguments with your own checks. Simply implement a class which implements the CheckBase interface, and pass an object of this class to addCheck().
In order to support other data types, you just need to implement a conversion function which reads the value from a istream and stores it in a variable of the corresponding type.
Example interface: istream& operator >>(istream& source, <type>& dest);
When used together with the Application() template, use this class as base class of your application main class, then evalArguments() is called automatically. The arguments must be specified in the constructor of your class then.
Please refer to the documentation for a complete description of all features.
Todo:
Don't use special member variables for control character handlers, implement them as 'starting characters' in a general way, so that afterwards also e.g. +<argument> is possible.
When using sub-groups, it should be possible to change the text displayed for the h/help arguments.
It should be possible to specify the pre- and post-usage text for sub-groups.
Also display checks like range, value-lists etc. in the usage.
Add handling for an argument like '–end-sub-group' which causes the processing in a sub-group to end and continue in the calling object.
This could be used to make sure that an argument is handled by the main object and not in the sub-group.
Additional flag for Handler: Sort arguments for usage.
Arguments that means: Everything that follows should not be treated as real program arguments anymore.
Example (here: first argument without a -): cmd [options ...] <servername> <cmd> [args ...] All following arguments are stored in the string provided with this parameter.
Due to the fact that addArgument() does not return the Handler object but the newly created TypedArg... object, it is not possible to use function call chaining like boost::program_options does.
To achieve something similar, the insertion operator could be overloaded for the class Handler, allowing for a syntax like
Handler ah;
ah << Argument(...)->setIsMandatory()-> ...
<< Argument(...)-> ...
Argument constraints: Relations. Support constraints like 'value of argument x must be less than value of argument y', e.g. start time < end time.
Change the logic of addCheck(): If multiple checks are added, a value is accepted if it matches at least one of these checks. Since lower and upper bound are already combined in the range check, I currently see no other need to specify two different checks that should be and'ed.
To make usage of program arguments easier: Argument that means "write all the following arguments into the program arguments file", e.g. "--create-prog-args [<filename>]"
Due to the fact that the range handling already produces values with the destination type, the existing check() methods cannot be applied (they expect a string parameter). Is it necessary/possible to fix this?
Add new range check that allows to specify a range string for the allowed values. Maybe need to rename the existing range check. Or simply replace it? Problem: The new range check would then also produce values with the destination type already ...
Maybe we want 'hidden argument groups'? Maybe this is not really necessary, check what happens on a group where all arguments are marked as hidden.
Pass the verbose flag to the assign methods and then print the verbose output there. This will cover all cases and also allows e.g. to print the second assignment if a pair is used.
For destination type vector: Add flag/feature that the contents of the vector should be cleared before the first value from the command line is assigned. Idea: vector is filled with default value(s), if the argument is used the default should be replaced by the new values.
Clean up the interface by removing all special addArgument()s for free values and a) simply document the case that an empty string should be passed b) and/or provide a constant 'free_value' (or so) that can be used.
Instead of having containers with short and/or the long argument as key, and multiple places to split an argument specification string into short and long string: Call ArgSpec, takes the string as parameter, stores it internally and splits it into short and/or long argument, finally can be used for comparison etc.
Flag and/or argument that changes the processing: Process all arguments and throw/exit at the end only. This would help to detect multiple errors in the argument string.
Add support for arguments with +/- logic?
Boolean flags with - would set the flag to false, with + it would be set to true.
What with other types? Maybe it would make sense to specify two different handlers, one for - and one for +? Or one handler with two different destinations, one for - and one for +? If +/- is distinguished on short arguments, what about long arguments?
Refactor typed arg for std::vector so that any std container can be used.
Similar solution that allows to use an std container with key/value pairs.
Check comments of constraints classes (all_of). All of: Use as dynamic constraint? Otherwise, all the arguments could simply be mandatory.
Add feature to specify the behaviour when the same argument is used multiple times (and cardinality is 1):
Error/Exception (as is), store the first value (ignore additional calls), store the last value.
Add test-feature: Process all arguments, print all errors.
Use different exit codes from evalArgumentErrorExit(), depending on the type of the exception that was called.
When multiple argument handlers are used with an argument group:
Optional parameter for the help argument, which allows to specify the (single) argument handler to display the help of.
Add pre- and post-argument list help texts also to argument handlers used in a group?
Since
0.2, 10.04.2016
Definition at line 220 of file handler.hpp.
Member Typedef Documentation
typedef std::vector< detail::IConstraint*> celma::prog_args::Handler::ConstraintCont private
Type of the container to store the global constrainst in.
Definition at line 640 of file handler.hpp.
typedef boost::function< void()> celma::prog_args::Handler::HandlerFunc
Type of the (storage handler of the) functions to call for control characters.
Definition at line 225 of file handler.hpp.
Member Enumeration Documentation
enum celma::prog_args::Handler::ArgResult protected
Function call result for evalSingleArgument():
Enumerator
arUnknown
Unknown argument for this instance (try with next).
arConsumed
Argument handled by this instance, proceed with next argument.
Definition at line 569 of file handler.hpp.
enum celma::prog_args::Handler::HandleFlags
List of flags to control the behaviour of this class:
Enumerator
hfHelpShort
Allows the argument '-h' to print the usage of the program.
hfHelpLong
Allows the argument '–help' to print the usage of the program.
hfReadProgArg
Specifies to read arguments from the optional program arguments file before parsing the command line arguments.
File: $HOME/.progargs/<progfilename>.pa
hfVerboseArgs
Produces verbose output when a value is assigned to a variable.
hfUsageHidden
Specifies that hidden arguments should be printed too in the usage.
hfArgHidden
Allows the argument '–print-hidden' to print the hidden arguments in the usage.
hfListArgVar
Adds the argument '–list-arg-vars' which, when used, prints the list of arguments and the names of the destination variables and their values.
hfUsageCont
Special flag originally for testing: Don't exit after printing the usage.
hfEndValues
Activates the argument '–endvalues' that is used to signal the end of a separate value list.
Definition at line 228 of file handler.hpp.
enum celma::prog_args::Handler::UsagePos
List of possible positions for the additional output.
Enumerator
upUnused
Initialization value.
upBeforeArgs
Position before the list of arguments.
upAfterArgs
Position after the list of arguments.
Definition at line 261 of file handler.hpp.
Constructor & Destructor Documentation
celma::prog_args::Handler::Handler (int flagSet = hfHelpShort | hfHelpLong, IUsageText * txt1 = nullptr, IUsageText * txt2 = nullptr) explicit
Constructor.
Parameters
[in] flagSet The set of flags. See enum HandleFlags for a list of possible values.
[in] txt1 Optional pointer to the object to provide additional text for the usage.
[in] txt2 Optional pointer to the object to provide additional text for the usage.
Since
0.3, 04.06.2016 (same interface, now implemented as delegating constructor)
0.2, 10.04.2016
Definition at line 63 of file handler.cpp.
celma::prog_args::Handler::Handler (std::ostream & os, std::ostream & error_os, int flag_set = hfHelpShort | hfHelpLong, IUsageText * txt1 = nullptr, IUsageText * txt2 = nullptr)
Constructor that allows to specify the output streams to write to.
Parameters
[in] os The stream to write normal out to.
[in] error_os The stream to write error output to.
[in] flag_set The set of flags. See enum HandleFlags for a list of possible values.
[in] txt1 Optional pointer to the object to provide additional text for the usage.
[in] txt2 Optional pointer to the object to provide additional text for the usage.
Since
0.3, 04.06.2016 (added parameters for output streams)
0.2, 10.04.2016
Definition at line 81 of file handler.cpp.
celma::prog_args::Handler::~Handler ()
Destructor, deletes dynamically allocated objects.
Since
0.2, 10.04.2016
Definition at line 129 of file handler.cpp.
Member Function Documentation
template<typename T > detail::TypedArgBase * celma::prog_args::Handler::addArgument (const std::string & arg_spec, T & dest, const std::string vname, const std::string & desc)
Adds a single-value argument.
Template Parameters
T The native type of the variable to store the value in.
Parameters
[in] arg_spec The arguments on the command line for this argument.
[in] dest The variable to store the value in.
[in] vname The name of the variable to store the value in.
Used for error reporting.
[in] desc The description of this argument.
Returns
The object managing this argument, may be used to apply further settings.
Since
0.2, 10.04.2016
Definition at line 855 of file handler.hpp.
Referenced by Handler().
template<typename T1 , typename T2 > detail::TypedArgBase * celma::prog_args::Handler::addArgument (const std::string & arg_spec, T1 & dest1, const std::string vname1, T2 & dest2, const std::string vname2, const T2 & value2, const std::string & desc)
Adds a single-value argument where an additional value is set on a second variable when the parameter is used.
Template Parameters
T1 The native type of the variable to store the argument value in.
T2 The native type of the second variable.
Parameters
[in] arg_spec The arguments on the command line for this argument.
[in] dest1 The variable to store the argument value in.
[in] vname1 The name of the variable to store the argument value in.
Used for error reporting.
[in] dest2 The variable to store the given value in.
[in] vname2 The name of the variable to store the given value in.
[in] value2 The value to store in the second variable.
[in] desc The description of this argument.
Returns
The object managing this argument, may be used to apply further settings.
Since
0.2, 10.04.2016
Definition at line 867 of file handler.hpp.
template<typename T > detail::TypedArgBase * celma::prog_args::Handler::addArgument (T & dest, const std::string vname, const std::string & desc)
Adds a free, single-value argument.
Template Parameters
T The native type of the variable to store the value in.
Parameters
[in] dest The variable to store the value in.
[in] vname The name of the variable to store the value in.
Used for error reporting.
[in] desc The description of this argument.
Returns
The object managing this argument, may be used to apply further settings.
Since
0.2, 10.04.2016
Definition at line 884 of file handler.hpp.
template<typename T , typename C > detail::TypedArgBase * celma::prog_args::Handler::addArgument (const std::string & arg_spec, const common::RangeDest< T, C > & dest, const std::string vname, const std::string & desc)
Adds a multi-value argument that supports a range definition string for the values.
Template Parameters
T The native type of the variable to store the value(s) in.
C The type of the container used to store the values in.
Parameters
[in] arg_spec The arguments on the command line for this argument.
[in] dest The variable to store the value(s) in.
[in] vname The name of the variable to store the value in.
Used for error reporting.
[in] desc The description of this argument.
Returns
The object managing this argument, may be used to apply further settings.
Since
0.2, 10.04.2016
Definition at line 894 of file handler.hpp.
template<typename T , typename C > detail::TypedArgBase * celma::prog_args::Handler::addArgument (const common::RangeDest< T, C > & dest, const std::string vname, const std::string & desc)
Adds a free, multi-value argument that supports a range definition string for the values.
Template Parameters
T The native type of the variable to store the value(s) in.
C The type of the container used to store the values in.
Parameters
[in] dest The variable to store the value(s) in.
[in] vname The name of the variable to store the value in.
Used for error reporting.
[in] desc The description of this argument.
Returns
The object managing this argument, may be used to apply further settings.
Since
0.2, 10.04.2016
Definition at line 906 of file handler.hpp.
detail::TypedArgBase * celma::prog_args::Handler::addArgument (const std::string & arg_spec, detail::ArgHandlerCallable fun, const std::string fname, const std::string & desc) inline
Adds an argument handler function that is called when an argument that does not accept any value is set.
Parameters
[in] arg_spec The arguments on the command line for this argument.
[in] fun The function to call for this argument.
Use the macros DEST_FUNCTION or DEST_METHOD to easily set up the correct call.
[in] fname The name of the function to call.
Used for error reporting.
[in] desc The description of this argument.
Returns
The object managing this argument, may be used to apply further settings.
Since
0.2, 10.04.2016
Definition at line 916 of file handler.hpp.
detail::TypedArgBase * celma::prog_args::Handler::addArgument (const std::string & arg_spec, detail::ArgHandlerCallableValue fun, const std::string fname, bool takes_value, const std::string & desc) inline
Adds an argument handler function that is called when an argument that may accept or requires a parameter is set.
Due to ambiguity problems there is no addArgument() version for using a free value for a callable. But you can achieve this easily by passing an empty string ("") as arg_spec.
Parameters
[in] arg_spec The arguments on the command line for this argument.
[in] fun The function to call for this argument.
This function must take an std::string as parameter.
Use the macros DEST_FUNCTION_VALUE or DEST_METHOD_VALUE to easily set up the correct call.
[in] fname The name of the function to call.
Used for error reporting.
[in] takes_value Dummy parameter used to distinguish from the non-value variant.
[in] desc The description of this argument.
Returns
The object managing this argument, may be used to apply further settings.
Since
0.2, 10.04.2016
Definition at line 927 of file handler.hpp.
detail::TypedArgBase * celma::prog_args::Handler::addArgument (const std::string & arg_spec, Handler * subGroup, const std::string & desc) inline
Adds a sub-group.
Note: Theoretically we could pass the object by reference, but then the compiler cannot distinguish anymore between this function and the variant to add an argument resulting in a function call.
Parameters
[in] arg_spec The arguments on the command line to enter/start the sub-group.
[in] subGroup The object to handle the sub-group arguments.
[in] desc The description of this sub-group argument.
Returns
The object managing this argument, may be used to apply further settings.
Since
0.2, 10.04.2016
Definition at line 939 of file handler.hpp.
detail::TypedArgBase * celma::prog_args::Handler::addArgumentEndValues (const std::string & arg_spec)
Adds an argument that can be used to mark the end of multiple, separate value list.
Parameters
[in] arg_spec The argument(s) on the command line for marking the end of a separate value list.
Returns
The object managing this argument, may be used to apply further settings.
Since
0.2, 10.04.2016
Definition at line 209 of file handler.cpp.
Referenced by Handler().
detail::TypedArgBase * celma::prog_args::Handler::addArgumentFile (const std::string & arg_spec)
Adds an argument that takes the path/filename of an argument file as parameter.
Parameters
[in] arg_spec The arguments on the command line for specifying the file with the arguments.
Returns
The object managing this argument, may be used to apply further settings.
Since
0.2, 10.04.2016
Definition at line 145 of file handler.cpp.
detail::TypedArgBase * celma::prog_args::Handler::addArgumentListArgVars (const std::string & arg_spec)
Adds an argument that prints the list of arguments, their destination variables and their values.
Same as setting the flag hfListArgVar, but allows to specify the argument.
Parameters
[in] arg_spec The argument(s) on the command line for printing the arguments and their destination variables.
Returns
The object managing this argument, may be used to apply further settings.
Since
0.2, 10.04.2016
Definition at line 188 of file handler.cpp.
Referenced by Handler().
detail::TypedArgBase * celma::prog_args::Handler::addArgumentPrintHidden (const std::string & arg_spec)
Adds an argument that activates printing of hidden arguments in the usage.
Same as setting the flag hfArgHidden, but allows to specify the argument.
Parameters
[in] arg_spec The argument(s) on the command line for activating printing the hidden arguments.
Returns
The object managing this argument, may be used to apply further settings.
Since
0.2, 10.04.2016
Parameters
[in] arg_spec The argument(s) on the command line for activating printing the hidden arguments.
Returns
The object managing this argument, may be used to apply further settings.
Since
0.2, 10.04.2016
Definition at line 167 of file handler.cpp.
Referenced by Handler().
void celma::prog_args::Handler::addConstraint (detail::IConstraint * ic)
Adds a constraint to the argument handler itself that affects multiple arguments.
The arguments specified in the constraint must already be defined.
Parameters
[in] ic Pointer to the object that handles the constraint.
Since
0.2, 10.04.2016
Definition at line 251 of file handler.cpp.
void celma::prog_args::Handler::addControlHandler (char ctrlChar, HandlerFunc hf)
Specifies the callback function for a control argument.
If no handler is defined for a control character, it is treated as error when found in an argument list.
Parameters
[in] ctrlChar The control character to specify the handler for.
[in] hf The handler to call when the control character is detected on the argument list.
Since
0.2, 10.04.2016
Definition at line 229 of file handler.cpp.
template<typename C , typename T > detail::TypedArgBase * celma::prog_args::Handler::addCustomArgument (const std::string & arg_spec, T & dest, const std::string vname, const std::string & desc)
Adds an argument with a custom destination type.
Template Parameters
C The custom class used to handle variables of the custom destination type. This class must be derived from the class TypedArgBase.
T The custom type of the destination variable to handle.
Parameters
[in] arg_spec The arguments on the command line for this argument.
[in] dest The variable to store the value(s) in.
[in] vname The name of the variable to store the value in.
Used for error reporting.
[in] desc The description of this argument.
Returns
The object managing this argument, may be used to apply further settings.
Since
0.2, 10.04.2016
Definition at line 954 of file handler.hpp.
bool celma::prog_args::Handler::argumentExists (char argChar) const protected
Checks if the specified argument is already used.
Parameters
[in] argChar The argument character to check.
Returns
true if the argument is already in use.
Since
0.2, 10.04.2016
Definition at line 599 of file handler.cpp.
bool celma::prog_args::Handler::argumentExists (const std::string & argString) const protected
Checks if the specified argument is already used.
Parameters
[in] argString The argument string to check.
Returns
true if the argument is already in use.
Since
0.2, 10.04.2016
Definition at line 611 of file handler.cpp.
void celma::prog_args::Handler::checkGlobalConstraints () const private
After all arguments were processed, call this method to iterate over all global constraints to check e.g.
if a required argument is missing.
Since
0.2, 10.04.2016
Definition at line 916 of file handler.cpp.
Referenced by evalArguments().
void celma::prog_args::Handler::checkMaxArgLen (size_t & maxArgLen) protected
Checks and sets the maximum argument length, needed to format the usage.
Parameters
[in,out] maxArgLen Maximum argument length as needed so far, may be increased if this class contains longer arguments.
Since
0.2, 10.04.2016
Definition at line 582 of file handler.cpp.
void celma::prog_args::Handler::checkMissingMandatoryCardinality () const protected
Checks if all mandatory arguments were set, and the cardinality requirements were met.
Since
0.2, 10.04.2016
Definition at line 567 of file handler.cpp.
void celma::prog_args::Handler::crossCheckArguments (const std::string ownName, const std::string & otherName, const Handler & otherAH) const protected
Compares the arguments defined in this object with those in otherAH and throws an exception if duplicates are detected.
Parameters
[in] ownName The symbolic name of this objects arguments.
[in] otherName The symbolic name of the the other objects arguments.
[in] otherAH The other object to check the argument list against.
Since
0.2, 10.04.2016
Definition at line 375 of file handler.cpp.
void celma::prog_args::Handler::endValueList () private
Called to mark the end of a value list: Sets mpLastArg to NULL.
Since
0.2, 10.04.2016
Definition at line 699 of file handler.cpp.
Referenced by addArgumentEndValues().
void celma::prog_args::Handler::evalArguments (int argc, char * argv[])
Iterates over the list of arguments and their values and stores the values in the corresponding destination variables.
The function also checks for missing, mandatory arguments, arguments wrongly used without a value etc. If an invalid value is passed for an argument, or if a mandatory argument is missing etc., an exception is thrown.
Parameters
[in] argc Number of arguments passed to the process.
[in] argv[] List of argument strings.
Exceptions
Exception as described above.
Since
0.2, 10.04.2016
The function also checks for missing, mandatory arguments, arguments wrongly used without a value etc. If an invalid value is passed for an argument, or if a mandatory argument is missing etc., an exception is thrown.
Parameters
[in] argc Number of arguments passed to the process.
[in] argv[] List of argument strings.
Since
0.2, 10.04.2016
Definition at line 279 of file handler.cpp.
Referenced by evalArgumentsErrorExit().
void celma::prog_args::Handler::evalArgumentsErrorExit (int argc, char * argv[], const std::string & prefix)
Same as evalArguments().
Difference is that this method catches exceptions, reports them on stderr and then exits the program.
In other words: If the function returns, all argument requirements and constraints were met.
Parameters
[in] argc Number of arguments passed to the process.
[in] argv List of argument strings.
[in] prefix Prefix text to print before the error message.
The prefix may be an empty string. If not, add a space at the end as separator to the following text.
Since
0.2, 10.04.2016
Definition at line 326 of file handler.cpp.
Handler::ArgResult celma::prog_args::Handler::evalSingleArgument (detail::ArgListParser::const_iterator & ai, const detail::ArgListParser::const_iterator & end) protected
Handles one argument.
Since this function is called from multiple sources, it must not throw an exception when e.g. an unknown argument is found. Exceptions may only be thrown if e.g. a known argument misses its value. Otherwise, in most cases arUnknown should be returned and the error handling left to the calling function.
Parameters
[in] ai Iterator that points to the argument to handle.
If the argument requires a value, the iterator is incremented, so it will point to the next argument when incremented again.
[in] end Iterator pointing to the end of the argument list.
Needed to check if a value is available.
Returns
Result of handling this argument.
Since
0.2, 10.04.2016
Definition at line 510 of file handler.cpp.
Referenced by iterateArguments(), and processArg().
void celma::prog_args::Handler::executeGlobalConstraints (const std::string & arg_spec) private
When an argument was identified, passes the argument specification to all global constraint objects to check if a constraint is violated.
Parameters
[in] arg_spec The argument specification.
Since
0.2, 10.04.2016
Definition at line 901 of file handler.cpp.
Referenced by handleIdentifiedArg().
void celma::prog_args::Handler::handleIdentifiedArg (detail::TypedArgBase * hdl, const std::string & arg_spec, const std::string & value = "") private
Called when a valid argument was identified.
Performs the actions that are common to all arguments:
Check argument constraints.
Check global constraints.
Produce verbose output if required.
Finally call calledAssign() for this argument.
Parameters
[in] hdl Pointer to the object that handles this argument.
[in] arg_spec The argument specification.
[in] value The value for the argument, empty string if not set.
Since
0.2, 10.04.2016
Definition at line 939 of file handler.cpp.
Referenced by evalSingleArgument(), and processArg().
detail::TypedArgBase * celma::prog_args::Handler::internAddArgument (detail::TypedArgBase * ah_obj, const std::string & arg_spec, const std::string & desc) private
Standard procedure for adding an argument handling object.
Parameters
[in] ah_obj Pointer to the object that handles the argument.
[in] arg_spec The specification of the argument.
[in] desc The description of the argument.
Returns
Pointer to the passed argument handling object.
Since
0.2, 10.04.2016
Definition at line 802 of file handler.cpp.
Referenced by addArgument(), addArgumentEndValues(), addArgumentFile(), addArgumentListArgVars(), addArgumentPrintHidden(), and addCustomArgument().
void celma::prog_args::Handler::iterateArguments (detail::ArgListParser & alp) private
Iterates over the arguments and evaluates them.
Parameters
[in] alp The parser object used to access the arguments.
Since
0.2, 10.04.2016
make me the current argument handler
Definition at line 711 of file handler.cpp.
Referenced by evalArguments(), and readArgumentFile().
void celma::prog_args::Handler::listArgVars () private
Prints the list of arguments and their destination variables.
Since
0.2, 10.04.2016
Definition at line 685 of file handler.cpp.
Referenced by addArgumentListArgVars().
template<typename T > Handler::ArgResult celma::prog_args::Handler::processArg (const T & arg, const std::string & argString, detail::ArgListParser::const_iterator & ai, const detail::ArgListParser::const_iterator & end) private
The handling of single character arguments and argument strings/names is of course completely the same, except for the argument and its type.
So, this template handles both types of arguments. Needed only in the implementation, so the template definition is in the source file too.
Template Parameters
T The type of the argument (character or string).
Parameters
[in] arg The argument (character/short or long).
[in] argString The argument character or string always in string format.
[in,out] ai The iterator pointing to the current argument. May be increased here (for values or argument groups).
[in] end Iterator pointing to the end of the argument list.
Returns
Result of handling the current argument.
Since
0.2, 10.04.2016
Definition at line 421 of file handler.cpp.
Referenced by evalSingleArgument().
void celma::prog_args::Handler::readArgumentFile (const std::string & pathFilename, bool reportMissing) private
Function to read arguments from a file.
Parameters
[in] pathFilename The (path and) file name to read from.
[in] reportMissing If set, the file should exist, an exception is thrown if the file could not be read.
Since
0.2, 10.04.2016
Definition at line 648 of file handler.cpp.
Referenced by addArgumentFile(), and readEvalFileArguments().
void celma::prog_args::Handler::readEvalFileArguments (const char * arg0) private
Tries to open the file with the program's name and read the arguments from this file.
Parameters
[in] arg0 The (path and) name of the program file.
Since
0.2, 10.04.2016
Definition at line 623 of file handler.cpp.
Referenced by evalArguments().
void celma::prog_args::Handler::setIsSubGroupHandler () inline private
Sets the flag that this object is used as sub-group handler.
Since
0.2, 10.04.2016
Definition at line 971 of file handler.hpp.
Referenced by addArgument().
void celma::prog_args::Handler::setUsageLineLength (int useLen) inline
Specifies the line length to use when printing the usage.
Parameters
[in] useLen The new line length to use.
The value must be in the range 60 <= useLen < 240.
Since
0.2, 10.04.2016
Definition at line 964 of file handler.hpp.
Referenced by celma::prog_args::detail::ArgumentContainer::setUsageLineLength().
void celma::prog_args::Handler::usage (IUsageText * txt1, IUsageText * txt2) private
Function to print the usage of a program (when requested through the arguments).
The additional parameters allow to print additional information.
Parameters
[in] txt1 Pointer to the object that prints the first text.
[in] txt2 Pointer to the object that prints the second text.
Since
0.2, 10.04.2016
Definition at line 757 of file handler.cpp.
Referenced by Handler().
bool celma::prog_args::Handler::validArguments (std::string & constraint_arg_list) const private
Checks each argument in the list if it is a valid/known argument.
If the argument specification in the list does not match the original specification of the argument (short and/or long), it is replaced in the constraint_arg_list.
Parameters
[in] constraint_arg_list .
Returns
.
Since
0.2, 10.04.2016
Definition at line 822 of file handler.cpp.
Referenced by addConstraint().
Friends And Related Function Documentation
friend class Groups friend
Class needs access to internals.
Definition at line 566 of file handler.hpp.
std::ostream& operator<< (std::ostream & os, const Handler & ah) friend
Prints the usage of this class.
Parameters
[out] os The stream to print to.
[in] ah The object to print the data of.
Returns
The stream.
Since
0.2, 10.04.2016
Definition at line 744 of file handler.cpp.
Member Data Documentation
const int celma::prog_args::Handler::AllFlags = hfHelpShort | hfHelpLong | hfReadProgArg static
Set of available standard/commonly used arguments.
Definition at line 271 of file handler.hpp.
const int celma::prog_args::Handler::AllHelp = hfHelpShort | hfHelpLong static
Set of all help arguments.
Definition at line 269 of file handler.hpp.
const int celma::prog_args::Handler::DebugFlags = hfVerboseArgs | hfListArgVar static
Flags for testing/debugging the module itself.
Definition at line 273 of file handler.hpp.
const int celma::prog_args::Handler::FullFlagSet static
Initial value:
= hfHelpShort | hfHelpLong | hfReadProgArg |
                                   hfVerboseArgs | hfUsageHidden | hfArgHidden |
                                   hfListArgVar | hfUsageCont
Complete set of all available arguments.
Definition at line 275 of file handler.hpp.
detail::ArgumentContainer celma::prog_args::Handler::mArguments private
The (top-level) arguments known by this class.
Definition at line 767 of file handler.hpp.
Referenced by argumentExists(), checkMissingMandatoryCardinality(), crossCheckArguments(), evalArguments(), evalSingleArgument(), internAddArgument(), listArgVars(), processArg(), and validArguments().
detail::ConstraintContainer celma::prog_args::Handler::mConstraints private
The current constraints, dynamically created through the arguments that were processed so far.
Definition at line 782 of file handler.hpp.
Referenced by evalArguments(), handleIdentifiedArg(), and iterateArguments().
detail::ArgumentDesc celma::prog_args::Handler::mDescription private
Storage for the arguments and their descriptions.
Definition at line 771 of file handler.hpp.
Referenced by addArgument(), checkMaxArgLen(), internAddArgument(), celma::prog_args::operator<<(), setUsageLineLength(), and usage().
std::ostream& celma::prog_args::Handler::mErrorOutput private
Stream to write error output to.
Definition at line 748 of file handler.hpp.
Referenced by evalArgumentsErrorExit().
ConstraintCont celma::prog_args::Handler::mGlobalConstraints private
Global constraints, i.e.
constraints that affect multiple arguments and/or are not triggered by a specific argument.
Definition at line 785 of file handler.hpp.
Referenced by addConstraint(), checkGlobalConstraints(), executeGlobalConstraints(), and ~Handler().
bool celma::prog_args::Handler::mIsSubGroupHandler private
Set when this object is used as argument handler for a sub-group.
Definition at line 779 of file handler.hpp.
Referenced by setIsSubGroupHandler(), and usage().
std::ostream& celma::prog_args::Handler::mOutput private
Stream to write output to.
Definition at line 746 of file handler.hpp.
Referenced by handleIdentifiedArg(), listArgVars(), and usage().
HandlerFunc celma::prog_args::Handler::mpClosingBracketHdlr private
Function called for a closing bracket ')'.
Definition at line 775 of file handler.hpp.
Referenced by addControlHandler(), crossCheckArguments(), and evalSingleArgument().
HandlerFunc celma::prog_args::Handler::mpExclamationMarkHdlr private
Function called for an exclamation mark '!'.
Definition at line 777 of file handler.hpp.
Referenced by addControlHandler(), crossCheckArguments(), and evalSingleArgument().
detail::TypedArgBase* celma::prog_args::Handler::mpLastArg private
Pointer to the last argument handler that was used.
Needed for processing multiple, separate values.
Definition at line 789 of file handler.hpp.
Referenced by endValueList(), evalArguments(), evalSingleArgument(), and processArg().
HandlerFunc celma::prog_args::Handler::mpOpeningBracketHdlr private
Function called for an opening bracket '('.
Definition at line 773 of file handler.hpp.
Referenced by addControlHandler(), crossCheckArguments(), and evalSingleArgument().
bool celma::prog_args::Handler::mPrintHidden private
Set when the flag hfUsageHidden was passed to the constructor.
Specifies if hidden arguments should be printed in the usage or not.
Definition at line 758 of file handler.hpp.
Referenced by addArgumentPrintHidden(), and usage().
bool celma::prog_args::Handler::mReadingArgumentFile private
Reading arguments from a file should not influence the cardinality checks, i.e.
it should be possible to overwrite a value from a file without triggering a 'too many values' exception.
Definition at line 793 of file handler.hpp.
Referenced by evalSingleArgument(), handleIdentifiedArg(), and readArgumentFile().
const bool celma::prog_args::Handler::mReadProgramArguments private
Set when the flag hfReadProgArg was passed to the constructor.
Then the default program arguments file is read before the command line arguments are evaluated.
Definition at line 752 of file handler.hpp.
Referenced by evalArguments().
detail::ArgumentContainer celma::prog_args::Handler::mSubGroupArgs private
Argument sub-groups.
Definition at line 769 of file handler.hpp.
Referenced by addArgument(), checkMissingMandatoryCardinality(), crossCheckArguments(), evalArguments(), listArgVars(), processArg(), and setUsageLineLength().
const bool celma::prog_args::Handler::mUsageContinues private
Set when the flag hfUsageCont was passed to the constructor.
Specifies that the program flow should continue after printing the usage.
Definition at line 761 of file handler.hpp.
Referenced by usage().
bool celma::prog_args::Handler::mUsagePrinted private
Set when the usage was printed.
Needed together with the flag mUsageContinues to bypass end-of-arguments checks so that evalArgument() can return.
Definition at line 765 of file handler.hpp.
Referenced by evalArguments(), and usage().
const bool celma::prog_args::Handler::mVerbose private
Set when the flag hfVerboseArgs was passed to the constructor.
Produces verbose output when a value is assigned to a variable.
Definition at line 755 of file handler.hpp.
Referenced by handleIdentifiedArg().
The documentation for this class was generated from the following files:
src/celma/prog_args/handler.hpp
src/library/prog_args/handler.cpp