Celma: celma::prog_args::detail::ArgumentContainer Class Reference
celma::prog_args::detail::ArgumentContainer Class Reference
Extracted from ArgumentHandler: Store an argument which may use the short argument format (character), the long format (string/name) or name.
#include <argument_container.hpp>
Public Member Functions
ArgumentContainer ()
Constructor.
void addArgument (TypedArgBase *argHandler, const std::string &argSpec)
Adds a new argument.
void checkMandatoryCardinality () const
After argument evaluating: Check that all mandatory arguments were set, and check that the cardinality requirements (if set) were met.
void checkArgMix (const std::string &ownName, const std::string &otherName, const ArgumentContainer &otherAH) const
Check this object and otherAH don't share any arguments.
TypedArgBase * findArg (char charArg) const
Searches if this single character argument is defined.
TypedArgBase * findArg (const std::string &longArg) const
Searches if this argument name is defined.
void setUsageLineLength (int useLen)
Specifies the line length to use when printing the usage.
bool empty () const
Returns if the class contains at least one argument.
Private Types
typedef std::shared_ptr< TypedArgBase > SharedArg
Store shared pointers to the handler objects.
typedef std::map< char, SharedArg > CharArgCont
Used to store the single character arguments and the corresponding handler objects.
typedef std::map< std::string, SharedArg > LongArgCont
Used to store the multi character (long) arguments and the corresponding handler objects.
Private Member Functions
void splitArgSpec (const std::string &argSpec, const SharedArg &sa)
Splits the argument specifyer string into single and long argument and stores it accordingly.
void addArgObj (const std::string &singleArgSpec, const SharedArg &sa)
Adds an object to either the single or multi character containers.
Private Attributes
CharArgCont mCharArgs
Single character arguments.
LongArgCont mLongArgs
Multi-character (long) arguments.
Friends
std::ostream & operator<< (std::ostream &os, const ArgumentContainer &ac)
Prints the contents of the container == list of all arguments.
Detailed Description
Extracted from ArgumentHandler: Store an argument which may use the short argument format (character), the long format (string/name) or name.
Since
0.2, 10.04.2016
Definition at line 35 of file argument_container.hpp.
Member Typedef Documentation
typedef std::map< char, SharedArg> celma::prog_args::detail::ArgumentContainer::CharArgCont private
Used to store the single character arguments and the corresponding handler objects.
Definition at line 101 of file argument_container.hpp.
typedef std::map< std::string, SharedArg> celma::prog_args::detail::ArgumentContainer::LongArgCont private
Used to store the multi character (long) arguments and the corresponding handler objects.
Definition at line 104 of file argument_container.hpp.
typedef std::shared_ptr< TypedArgBase> celma::prog_args::detail::ArgumentContainer::SharedArg private
Store shared pointers to the handler objects.
Definition at line 97 of file argument_container.hpp.
Constructor & Destructor Documentation
celma::prog_args::detail::ArgumentContainer::ArgumentContainer ()
Constructor.
Since
0.2, 10.04.2016
Definition at line 41 of file argument_container.cpp.
Member Function Documentation
void celma::prog_args::detail::ArgumentContainer::addArgObj (const std::string & singleArgSpec, const SharedArg & sa) private
Adds an object to either the single or multi character containers.
Parameters
[in] singleArgSpec The string with the single or multi-character argument.
[in] sa The object to handle this argument.
Since
0.2, 10.04.2016
Definition at line 240 of file argument_container.cpp.
Referenced by splitArgSpec().
void celma::prog_args::detail::ArgumentContainer::addArgument (TypedArgBase * argHandler, const std::string & argSpec)
Adds a new argument.
Parameters
[in] argHandler The object used to handle this argument.
[in] argSpec The argument character, string or both.
Since
0.2, 10.04.2016
Definition at line 53 of file argument_container.cpp.
Referenced by celma::prog_args::Handler::addArgument(), and celma::prog_args::Handler::internAddArgument().
void celma::prog_args::detail::ArgumentContainer::checkArgMix (const std::string & ownName, const std::string & otherName, const ArgumentContainer & otherAH) const
Check this object and otherAH don't share any arguments.
Parameters
[in] ownName The symbolic name of this argument group.
[in] otherName The symbolic name of the other object's argument group.
[in] otherAH The other object to check the argument against.
Since
0.2, 10.04.2016
Definition at line 96 of file argument_container.cpp.
Referenced by celma::prog_args::Handler::crossCheckArguments().
void celma::prog_args::detail::ArgumentContainer::checkMandatoryCardinality () const
After argument evaluating: Check that all mandatory arguments were set, and check that the cardinality requirements (if set) were met.
Since
0.2, 10.04.2016
Definition at line 69 of file argument_container.cpp.
Referenced by celma::prog_args::Handler::checkMissingMandatoryCardinality(), and celma::prog_args::Handler::evalArguments().
bool celma::prog_args::detail::ArgumentContainer::empty () const inline
Returns if the class contains at least one argument.
Returns
true if the class doesn't contain any argument(s).
Since
0.2, 10.04.2016
Definition at line 132 of file argument_container.hpp.
Referenced by celma::prog_args::Handler::listArgVars().
TypedArgBase * celma::prog_args::detail::ArgumentContainer::findArg (char charArg) const
Searches if this single character argument is defined.
Parameters
[in] charArg The argument character to check.
Returns
Pointer to the argument handler object if the argument is defined, NULL otherwise.
Since
0.2, 10.04.2016
Definition at line 128 of file argument_container.cpp.
Referenced by celma::prog_args::Handler::argumentExists(), celma::prog_args::Handler::evalSingleArgument(), celma::prog_args::Handler::processArg(), and celma::prog_args::Handler::validArguments().
TypedArgBase * celma::prog_args::detail::ArgumentContainer::findArg (const std::string & longArg) const
Searches if this argument name is defined.
Parameters
[in] longArg The argument name to check.
Returns
Pointer to the argument handler object if the argument is defined, NULL otherwise.
Since
0.2, 10.04.2016
Definition at line 144 of file argument_container.cpp.
void celma::prog_args::detail::ArgumentContainer::setUsageLineLength (int useLen)
Specifies the line length to use when printing the usage.
Used when this container is used to store te sub-group arguments.
Parameters
[in] useLen The new line length to use.
The value must be in the range 60 <= useLen < 240.
Since
0.2, 10.04.2016
Definition at line 184 of file argument_container.cpp.
Referenced by celma::prog_args::Handler::setUsageLineLength().
void celma::prog_args::detail::ArgumentContainer::splitArgSpec (const std::string & argSpec, const SharedArg & sa) private
Splits the argument specifyer string into single and long argument and stores it accordingly.
Parameters
[in] argSpec The string with the short, long or both arguments.
[in] sa The object to handle these argument(s).
Since
0.2, 10.04.2016
Definition at line 214 of file argument_container.cpp.
Referenced by addArgument().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const ArgumentContainer & ac) friend
Prints the contents of the container == list of all arguments.
Parameters
[out] os The stream to write to.
[in] ac The object to dump the data of.
Returns
The stream as passed in.
Since
0.2, 10.04.2016
Definition at line 278 of file argument_container.cpp.
Member Data Documentation
CharArgCont celma::prog_args::detail::ArgumentContainer::mCharArgs private
Single character arguments.
Definition at line 121 of file argument_container.hpp.
Referenced by addArgObj(), checkArgMix(), checkMandatoryCardinality(), empty(), findArg(), celma::prog_args::detail::operator<<(), and setUsageLineLength().
LongArgCont celma::prog_args::detail::ArgumentContainer::mLongArgs private
Multi-character (long) arguments.
Definition at line 123 of file argument_container.hpp.
Referenced by addArgObj(), checkArgMix(), checkMandatoryCardinality(), empty(), findArg(), celma::prog_args::detail::operator<<(), and setUsageLineLength().
The documentation for this class was generated from the following files:
src/celma/prog_args/detail/argument_container.hpp
src/library/prog_args/detail/argument_container.cpp